CREATE TABLE IF NOT EXISTS imaweb_tools_migrations
(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
    RUN_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT imaweb_tools_migrations_pk
        PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS imaweb_tools_redirect
(
    ID INT AUTO_INCREMENT,
    ACTIVE CHAR(1) NOT NULL DEFAULT "Y",
    SITE_ID VARCHAR(8) NOT NULL,
    OLD_URL VARCHAR(255) NOT NULL,
    NEW_URL VARCHAR(255) NOT NULL,
    TYPE INT NOT NULL,
    CONSTRAINT imaweb_redirect_pk
        PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IMAWEB_REDIRECT_OLD_URL_UINDEX
    ON imaweb_tools_redirect (OLD_URL);


